site_name: DuFuzzyLogic Documentation
site_url: https://rxlaboratory.org/tools/dufuzzylogic/
repo_url: https://github.com/Nico-Duduf/DuFuzzyLogic
edit_uri: edit/master/src-docs/docs/
site_description: The DuFuzzyLogic documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2020-2022 <a href="https://duduf.com">Nicolas Dufresne</a>'
use_directory_urls: false
theme:
    name: null
    custom_dir: 'cinder'
    colorscheme: zenburn
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - fenced_code
    - attr_list
extra_css:
    - style.csss
    - video.css
extra_javascript:
    - video.js
    - meta.js
    - collapser.js
site_dir: ../docs/
dev_addr: '127.0.0.1:8001'
nav:
    - 1.0.0: index.md
    - Fuzzy Logic:
        - Introduction: Home.md
        - Advantages: Advantages.md
        - Fuzzification: Fuzzification.md
        - Shapes: Shapes.md
        - Rules:
            - Logic operators: Rules.md
            - Quantifiers: Quantifiers.md
        - Crispification: Crispification.md
    - API:
        - Examples (JavaScript):
            - Color Redness: Redness.md
            - HVAC Complex example: AirConditioning.md
        - Existing Libraries: Libraries.md
        - JavaScript Reference: https://dufuzzylogic.rxlab.io/js-reference/index.html
        - After Effects Expressions: https://github.com/Rainbox-dev/DuAEF_ExpressionLib
    - ...:
        - License:
            - GNU GPLv3: gnu-gpl.md
            - Documentation license: doc-license.md
        - Contact: https://rainboxlab.org/about/contact/
        - Donate: https://rainboxlab.org/about/donate/